#!/bin/bash
# ./0-transfer_file ~/sed_test_file 35.237.199.102 ubuntu /home/oluwaseun/.ssh/id_rsa
if (($# \< 3))
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -i $4 $1 $3@$2:
fi
