#!/bin/bash
sudo apt-get update
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sudo chmod 777  /var/www/html/index.nginx-debian.html
sudo echo 'Hello World!' > /var/www/html/index.nginx-debian.html
